name: ddist
dependencies:
  archive: ^1.0.0
  args: ^1.0.0
  cli_util: ^0.1.3
  dart2_constant: ^1.0.0
  glob: ^1.0.0
  io: ^0.3.2
  logging: ^0.11.0
  path: ^1.4.0
  system_info: ^0.0.6
  yaml: ^2.0.0
executables:
  ddist: main